name: Test container
inputs:
  container:
    required: true
    type: string

runs:
  using: "composite"
  steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: addnab/docker-run-action@v3
        with:
          registry: gcr.io
          image: ${{ container }}
          options: "-v ${{ github.workspace }}:${{github.workspace}} -w ${{github.workspace}}"
          run: |
            echo "SNAKES"
            find
            echo $(readlink -f pwd)
            env
