name: Try and dist stuff
on: [ push ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - debug
          - release
    container:
      image: rust:slim-bookworm
    steps:
      - uses: actions/checkout@v4
      - run: cargo build --${{matrix.target}}
      - uses: actions/upload-artifact@v4
        with:
          name: build-${{matrix.target}}
          path: target/${{matrix.target}}/github-workflow-test
  publish:
    needs: [build-and-push-image]
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - run: find
      - run: |
          gh release delete latest --yes || true
          git push origin :latest || true
      - run: >
          gh release create latest
          --prerelease
          --target $GITHUB_SHA build-*/*
