name: Test container
on:
   workflow_call:
    inputs:
      container:
        required: true
        type: string

jobs:
  test-container:
    runs-on: ubuntu-latest
    needs: ["build-and-push-image"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: addnab/docker-run-action@v3
        with:
          registry: gcr.io
          image: ${{ container }}
          options: "-v ${{ github.workspace }}:${{github.workspace}} -w ${{github.workspace}}"
          run: |
            echo "SNAKES"
            find
            echo $(readlink -f pwd)
            env
