# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Misc test
on: [ push, pull_request, workflow_dispatch]

jobs:
  test-run-latest:
    strategy:
      fail-fast: false
      matrix:
        on: [ubuntu-latest, ubuntu-22.04]
    runs-on: ${{matrix.on}}
    steps:
      - name: lscpu
        run: |
          sudo ls -l /dev
      - name: image environment
        run: |
          sudo ls -l /dev
      - name: journal
        run: |
          uname -a
          sudo journalctl -b -k
      - name: sysfs
        run: |
          sudo egrep . /sys/class/dmi/id/* || true
